### PR TITLE
Mark ThreadGroups created by FailOnTimeout as daemon groups

### LINKED ISSUE #1652: Timeout ThreadGroups should not be destroyed
#### Environment:

Eclipse: Version: 2019-09 R (4.13.0), Build id: 20190917-1200
EclEmma 3.1.2.201903112331	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
JUnit 4.13
Windows 10 x64
Java 1.8u241

#### Issue:

I've run into an odd error while running coverage on an unit test having some methods use Google Guava's CacheBuilder in Eclipse. The coverage fails with the error code 5013 and error report indicating java.net.SocketException: Connection reset. If I remove these methods, the coverage succeeds.

If I revert back to JUnit 4.12, both the test file and the individual test succeeds in producing the coverage data.

Example method:
https://github.com/ReactiveX/RxJava/blob/5f6aafcbaa97f330ad2007f4ad02c5e33db8914b/src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java#L1917

This is where the cache is created:
https://github.com/ReactiveX/RxJava/blob/5f6aafcbaa97f330ad2007f4ad02c5e33db8914b/src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java#L2194

#### Additional details:

- If I run "gradlew test jacocoTestReport" on the entire project, it succeeds in creating the report HTML apparently.
- If I run "Coverage As > JUnit test" on the entire project from Eclipse, it fails with the same 5013 error.
- If I run any other test class/package/method in the project, the coverage is created successfully.

Please advise.

### PR DESCRIPTION
**Pull request by kcooney**
Fixes #1652

### CODE REVIEW

**Review by marcphilipp — APPROVED** [review]

File: src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java [hunk 1]
```diff
@@ -121,28 +121,21 @@ public void evaluate() throws Throwable {
...
-            } catch (InterruptedException e) {
-                Thread.currentThread().interrupt();
-            }
-            try {
-                threadGroup.destroy();
-            } catch (IllegalThreadStateException e) {
-                // If a thread from the group is still alive, the ThreadGroup cannot be destroyed.
+                threadGroup.setDaemon(true);
+            } catch (SecurityException e) {
                 // Swallow the exception to keep the same behavior prior to this change.
```
Comment (stefanbirkner) [inline src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java:128]: The term "this change" is a little bit unspecific now. Can you change it to
```suggestion
                // Swallow the exception to keep the same behavior as in JUnit 4.12.
```

**Review by stefanbirkner — CHANGES_REQUESTED** [review]

**Comment by kcooney** [comment]
FYI: I updated the test to verify that the `ThreadGroup` is destroyed (and verified by hand that if I don't mark it as a daemon, the `ThreadGroup` is not destroyed).

**Comment by kcooney** [comment]
So apparently marking the `ThreadGroup` as a daemon will not result in it being destroyed in all versions of the JDK (at least not immediately after the only thread in the group completes). I'm guessing that in some versions of the JDK it would be destroyed after a delay.

**Comment by marcphilipp** [comment]
Which versions did you try?

**Comment by kcooney** [comment]
It was a race condition. The test needed to join on the inner thread before checking the `ThreadGroup` status.

Lots of changes to squash, but leaving as-is for now so you can all see the changes.

**Comment by stefanbirkner** [comment]
@kcooney Can you please have a look at #1690. I changed the test that checks that the thread group is destroyed. IMO it is now checking the behavior that we are looking for. What do you think? It you are ok with the new test then your PR can be reduced to the change in FailOnTimeout and does not need to change the test.

**Comment by kcooney** [comment]
@stefanbirkner the test in this pull now verifies that the thread group is destroyed. It has a few unnecessary assertions (I was trying to determine why it passed on my machine but not in the CI build). I would be happy to remove the now-unnecessary extra assertions.

Even so, the test in this pull seems a bit more straight-forward than the one in yours. WDYT?

**Comment by stefanbirkner** [comment]
I tend to like your approach more. If I change my opinion I can still create another PR.

**Review by stefanbirkner — APPROVED** [review]

**Comment by stefanbirkner** [comment]
I changed the explanation in #1690 and removed changing the test.

File: src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java [hunk 2]
```diff
@@ -121,28 +121,21 @@ public void evaluate() throws Throwable {
...
-                thread.join(1);
-            } catch (InterruptedException e) {
-                Thread.currentThread().interrupt();
-            }
-            try {
-                threadGroup.destroy();
-            } catch (IllegalThreadStateException e) {
-                // If a thread from the group is still alive, the ThreadGroup cannot be destroyed.
-                // Swallow the exception to keep the same behavior prior to this change.
+                threadGroup.setDaemon(true);
```
Comment (j256) [inline src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java:126]: There should be a comment here pointing to this pull request and explaining why they should be daemon.

Comment (stefanbirkner) [reply src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java:126]: #1691 adds an explanation

Comment (j256) [reply src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java:126]: Certainly does.  Thanks.

**Review by Tuneabq — COMMENTED** [review]
👍

File: src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java (hunk 1 above)
Comment (shivam11-u) [reply src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java]: How

Comment (kcooney) [reply src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java]: @shivam11-u I'm not quite sure what your question is, but if you are wondering how this change "keeps the same behavior" code here is catching `SecurityException` it's because it's possible that JUnit is running in an environment
