### PR TITLE
Handle AssumptionViolatedException in @Parameters method

### LINKED ISSUE #1329: assumeTrue doesn't work in @Parameters methods
My test class loads some expensive resources in the parameters function, so I want to skip that step if the entire class of tests is going to be skipped anyway. However, when I use `assumeTrue` in the parameters function the tests fail with the following:

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    at org.junit.Assume.assumeThat(Assume.java:95)
    at org.junit.Assume.assumeTrue(Assume.java:41)
    at ExampleTest.getParams(ExampleTest.java:17)
```

I am running JUnit 4.12 within Eclipse. MWE below:

```
import static org.junit.Assume.assumeTrue;

import java.util.Collection;
import java.util.Collections;

import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class ExampleTest {

    @Parameters(name = "{index}: {1}")
    public static Collection<Object[]> getParams() {
//      assumeTrue(false);//bad
        return Collections.emptyList();
    }

    public ExampleTest(){
        assumeTrue(false);//okay
    }
}
```

### PR DESCRIPTION
**Pull request by panchenko**
Fixes #1329

### CODE REVIEW

File: src/main/java/org/junit/runners/Parameterized.java [hunk 1]
```diff
@@ -365,7 +396,13 @@ private TestWithParameters createTestWithNotNormalizedParameters(
         @SuppressWarnings("unchecked")
         private static List<Object> allParameters(
                 TestClass testClass, FrameworkMethod parametersMethod) throws Throwable {
-            Object parameters = parametersMethod.invokeExplosively(null);
+            Object parameters;
+            try {
+                parameters = parametersMethod.invokeExplosively(null);
+            } catch (AssumptionViolatedException e) {
```
Comment (kcooney) [inline src/main/java/org/junit/runners/Parameterized.java]: Couldn't you catch this exception in the caller (`RunnersFactory`)? If the exception gets caught, you can set a field in `RunnersFactory` named `runnerOverride` to a new `AssumptionViolationRunner`. If `runnerOverride` is set it would be returned from `RunnersFactory.createRunners()`.

As a bonus, we could possibly catch any exception from there, and for the exceptions that aren't `AssumptionViolatedException ` use `ErrorReportingRunner`.

Comment (panchenko) [inline src/main/java/org/junit/runners/Parameterized.java]: I've implemented the first part. 

`ErrorReportingRunner` is already applied in `RunnerBuilder.safeRunnerForClass()`, seems like we should not care about other exceptions.

**Comment by kcooney** [comment]
@panchenko Thanks! Could you update the release notes on the wiki?

**Comment by garfieldnate** [comment]
Thank you!

**Comment by panchenko** [comment]
@kcooney I've updated release notes for this.
