### PR TITLE
Clear thread interrupt status after each test

### LINKED ISSUE #1365: Interrupted test cases cause random failures with thread reuse
Whenever a test case is interrupted (Thread.interrupt()), the test runner thread seems to stay in interrupted state. This causes random failures later when the thread is reused for other test cases.

Expected behaviour: When the thread is reused, interrupted flag for the thread is cleaned before starting a new test case. This can be done by calling `Thread.interrupted()`, which returns the interrupted state, and clears the interrupted flag.

The following code should reproduce the problem, given that test1 is run before test2

``` java
import org.junit.Test;

public class ThreadTest {
  @Test
  public void test1() {
    Thread.currentThread().interrupt();
  }

  @Test
  public void test2() throws InterruptedException {
    Thread.sleep(1000);
  }
}
```

The problem I encountered is similar to the one described in https://www.thoughtwire.com/junit-interupt/

### PR DESCRIPTION
**Pull request by marcphilipp**
The thread interrupt status flag is now cleared from `classBlock()` and
`methodBlock()`. The flag is cleared after each test case completes and
after `AfterClass` methods and `ClassRules` have been executed.

Fixes #1365.

---

Originally submitted as #1569.

### CODE REVIEW

**Comment by kcooney** [comment]
I unfortunately do not have time to help with JUnit at this time

File: src/test/java/org/junit/tests/running/classes/ThreadsTest.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+                interruptedFlags.add(Thread.currentThread().isInterrupted());
+            }
+        });
+
+        Request request = new Request() {
+            @Override
+            public Runner getRunner() {
+                try {
+                    return new BlockJUnit4ClassRunner(TestWithInterruptFromAfterClass.class) {
+                    };
```
Comment (panchenko) [inline src/test/java/org/junit/tests/running/classes/ThreadsTest.java]: is this anonymous class necessary/intentional?

File: src/test/java/org/junit/tests/running/classes/ThreadsTest.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        }
+
+    }
+
+    @Test
+    public void currentThreadInterruptedStatusIsClearedAfterEachTestExecution() {
+        core.addListener(new RunListener() {
+            @Override
+            public void testFinished(Description description) {
+                interruptedFlags.add(Thread.currentThread().isInterrupted());
```
Comment (panchenko) [inline src/test/java/org/junit/tests/running/classes/ThreadsTest.java]: 1) This listener is duplicated in both tests. As JUnitCore is a field, might be add this listener from a `@Before` method?
2) Another thing this listener can do is just `assertFalse()`, WDYT?

Comment (marcphilipp) [reply src/test/java/org/junit/tests/running/classes/ThreadsTest.java]: The listeners actually implement a different method but have the same implementation. Just doing `assertFalse()` would have the downside that we're not checking that the listener was actually called.

File: src/test/java/org/junit/tests/running/classes/ThreadsTest.java (hunk 1 above)
Comment (marcphilipp) [reply src/test/java/org/junit/tests/running/classes/ThreadsTest.java]: Good catch, it wasn't necessary. I simplified the test in 20a130ef8dfdd533202e9e5938ccc111b6e832f1.
